application: vvmanager
version: alpha
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /img
    static_dir: img
  - url: /bower_components
    static_dir: bower_components
  - url: /src
    static_dir: src
  - url: /js
    static_dir: js
  - url: /_/.*
    script: stub_data.handler.stub_handler
  - url: /
    static_files: index.html
    upload: index.html
